parameters:
    ask_sphinx_search.api.class:                        SphinxClient
    ask_sphinx_search.manager.class:                    ASK\SphinxSearch\SphinxManager

services:
    ask_sphinx_search.api:
        class:                                      %ask_sphinx_search.api.class%

    ask_sphinx_search.manager:
        class:                                      %ask_sphinx_search.manager.class%
        arguments:
            -                                       @ask_sphinx_search.api
            -                                       []