parameters:
    ask_sphinx_search.api.class:                        SphinxClient
    ask_sphinx_search.manager.class:                    ASK\SphinxSearch\SphinxManager

services:
    ask_sphinx_search.api:
        class:                                          %ask_sphinx_search.api.class%

    ask_sphinx_search.manager:
        class:                                          %ask_sphinx_search.manager.class%
        arguments:
            -                                           @ask_sphinx_search.api
            -                                           []

    data_collector.sphinx:
        class: ASK\SphinxSearchBundle\DataCollector\SphinxDataCollector
        arguments:
            -                                           @ask_sphinx_search.manager
        tags:
            -                                           { name: data_collector, template: "ASKSphinxSearchBundle:Collector:layout.html.twig", id: "sphinx" }